/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RNORM_H_RPCGEN
#define _RNORM_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define RNORM_PROG ((rpc_uint)1234567)
#define RNORM_VARS ((rpc_uint)1)

#ifdef __cplusplus
#define MYPI ((rpc_uint)1)
extern "C" double * mypi_1(void *, CLIENT *);
extern "C" double * mypi_1_svc(void *, struct svc_req *);
#define MYEXP ((rpc_uint)2)
extern "C" double * myexp_1(int *, CLIENT *);
extern "C" double * myexp_1_svc(int *, struct svc_req *);

#elif __STDC__
#define MYPI ((rpc_uint)1)
extern  double * mypi_1(void *, CLIENT *);
extern  double * mypi_1_svc(void *, struct svc_req *);
#define MYEXP ((rpc_uint)2)
extern  double * myexp_1(int *, CLIENT *);
extern  double * myexp_1_svc(int *, struct svc_req *);

#else /* Old Style C */
#define MYPI ((rpc_uint)1)
extern  double * mypi_1();
extern  double * mypi_1_svc();
#define MYEXP ((rpc_uint)2)
extern  double * myexp_1();
extern  double * myexp_1_svc();
#endif /* Old Style C */

#endif /* !_RNORM_H_RPCGEN */
